name: Preview Release

on:
  push:
    branches:
      - preview

jobs:
  preview:
    name: Preview Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Preview Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          bun run release
          echo "Preview release completed"

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1
            });

            const latestRelease = releases[0];
            const releaseInfo = latestRelease ? `
            ## Preview Release Created

            🎉 New preview version: **${latestRelease.tag_name}**

            ### Release Notes
            ${latestRelease.body}

            [View Release](${latestRelease.html_url})
            ` : '## No release was created';

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: releaseInfo
            });
